# Generated by Django 2.1.dev20180211004558 on 2018-02-13 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_table',
            fields=[
                ('Album_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Album_Name', models.CharField(max_length=500, null=True)),
                ('Album_Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating_table',
            fields=[
                ('Rating_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Ratings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Songs_table',
            fields=[
                ('Song_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Song_Name', models.CharField(max_length=500, null=True)),
                ('Artist_Name', models.CharField(max_length=500, null=True)),
                ('Views_No', models.IntegerField()),
                ('Album_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mapp.Album_table')),
            ],
        ),
        migrations.AddField(
            model_name='rating_table',
            name='Song_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mapp.Songs_table'),
        ),
        migrations.AddField(
            model_name='rating_table',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
