# Generated by Django 2.1.dev20180211004558 on 2018-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_table',
            name='Album_Year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating_table',
            name='Ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='songs_table',
            name='Views_No',
            field=models.IntegerField(null=True),
        ),
    ]
