# Generated by Django 2.1.dev20180211004558 on 2018-02-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapp', '0002_auto_20180213_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs_table',
            name='Views_No',
            field=models.IntegerField(default=0),
        ),
    ]
